USE RentalOrderOperationalDB;
GO

BULK INSERT Category
FROM 'C:\SQLData\Category.csv'
WITH (FORMAT='CSV', FIRSTROW=2);

BULK INSERT SubCategory
FROM 'C:\SQLData\SubCategory.csv'
WITH (FORMAT='CSV', FIRSTROW=2);

BULK INSERT Item
FROM 'C:\SQLData\Item.csv'
WITH (FORMAT='CSV', FIRSTROW=2);

BULK INSERT ItemInstance
FROM 'C:\SQLData\ItemInstance.csv'
WITH (FORMAT='CSV', FIRSTROW=2);

BULK INSERT Address
FROM 'C:\SQLData\Address.csv'
WITH (FORMAT='CSV', FIRSTROW=2);

BULK INSERT Customer
FROM 'C:\SQLData\Customer.csv'
WITH (FORMAT='CSV', FIRSTROW=2);

BULK INSERT Location
FROM 'C:\SQLData\Location.csv'
WITH (FORMAT='CSV', FIRSTROW=2, KEEPNULLS);

BULK INSERT Employee
FROM 'C:\SQLData\Employee.csv'
WITH (FORMAT='CSV', FIRSTROW=2);

BULK INSERT Rental
FROM 'C:\SQLData\Rental.csv'
WITH (FORMAT='CSV', FIRSTROW=2, KEEPNULLS);

BULK INSERT RentalLineOrder
FROM 'C:\SQLData\RentalLineOrder.csv'
WITH (FORMAT='CSV', FIRSTROW=2);


